language: node_js
node_js:
  - "14"

# safelist
branches:
  only:
  - master
  - develop

os:
  - linux
  - osx
  - windows
dist: bionic

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install g++-multilib;
      sudo apt-get install -y build-essential;
      sudo apt-get install libudev-dev;
    fi
  - if [ $TRAVIS_OS_NAME == "windows" ]; then
      choco install python --version 3.7;
      python3 --version;
      python3 -m pip3 install --upgrade pip;
    fi
  - npm install -g vsce
  - npm install -g node-gyp
  - npm install -g gulp

install:
  - npm install

script:
  - gulp build --electron="12.0.4" --token="$API_TOKEN" --tag="downloads"
